### ISSUE TITLE
Reload command

### ISSUE THREAD

**Issue by SlimeDog** [Mas281/ForgeModBlocker#7]
Please add a **forgemodblocker reload** command.

**Comment by Mas281** [comment]
Thanks, will add this in the next update along with LiteLoader detection support!

**Comment by SlimeDog** [comment]
In case the intent isn't clear, **forgemodblocker reload** should adjust the configuration based on the current values found in config.yml, and restart the plugin (if necessary). It should be available at the console and (filtered by appropriate permission) in-game.

**Comment by Mas281** [comment]
Added in #8
